# Generated by Django 5.0.10 on 2025-01-29 10:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0010_openaikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the scenario', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the scenario shown to users')),
                ('system_prompt', models.TextField(help_text='System prompt that sets up the game context and rules', validators=[django.core.validators.MinLengthValidator(10)])),
                ('initial_prompt', models.TextField(help_text='Initial prompt to start the story', validators=[django.core.validators.MinLengthValidator(10)])),
                ('order', models.IntegerField(default=10, help_text='Order in which scenarios are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active scenarios will be shown to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the story (generated or user-provided)', max_length=200)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_stories', to='llm_caller.llmmodel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='llm_caller.gamescenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Game stories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('system_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='llm_caller.gamestory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
