# Generated by Django 5.0.10 on 2025-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0011_gamescenario_gamestory_gameinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinteraction',
            old_name='user_input',
            new_name='system_input',
        ),
        migrations.RenameField(
            model_name='gameinteraction',
            old_name='system_response',
            new_name='system_output',
        ),
        migrations.RemoveField(
            model_name='gamescenario',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gamescenario',
            name='initial_prompt',
        ),
        migrations.RemoveField(
            model_name='gamescenario',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='gamestory',
            name='scenario',
        ),
        migrations.AddField(
            model_name='gameinteraction',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='gamescenario',
            name='genre',
            field=models.CharField(default='', help_text='Genre of the scenario (e.g., Fantasy, Sci-Fi)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamestory',
            name='genre',
            field=models.CharField(default='', help_text='Genre of the story (e.g., Fantasy, Sci-Fi)', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='system_prompt',
            field=models.TextField(default='You are AI Text Game Master. You are responsible for creating a story for the user.\nYou will be given a genre and a model name. You will then create a story for the user.\nYou will then interact with the user and respond to their input.\nYou start the story with a one-line description of the story.\nThen you will ask the user to select a character from the list of 3 characters.\n', help_text='The system prompt instructs the model to generate JSON format.'),
        ),
    ]
