# Generated by Django 5.0.10 on 2025-02-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0012_rename_user_input_gameinteraction_system_input_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinteraction',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='TextExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('context_text', models.TextField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='llm_caller.gamestory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
