# Generated by Django 5.0.10 on 2025-02-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0013_alter_gameinteraction_role_textexplanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescenario',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='gamescenario',
            name='title',
        ),
        migrations.AddField(
            model_name='gamescenario',
            name='category',
            field=models.CharField(choices=[('genre', 'Genre'), ('sub-genre', 'Sub-Genre')], default='genre', help_text='Category of the scenario', max_length=100),
        ),
        migrations.AddField(
            model_name='gamescenario',
            name='example',
            field=models.TextField(blank=True, help_text='Example movies/books/etc. of this genre/sub-genre'),
        ),
        migrations.AddField(
            model_name='gamescenario',
            name='name',
            field=models.CharField(default='', help_text='Name of the scenario (e.g., Fantasy, Sci-Fi)', max_length=100),
            preserve_default=False,
        ),
    ]
