# Generated by Django 5.0.10 on 2025-02-02 08:33

from django.db import migrations, models

def set_existing_records_to_completed(apps, schema_editor):
    TextExplanation = apps.get_model('llm_caller', 'TextExplanation')
    TextExplanation.objects.all().update(status='completed')

class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0016_llmconfig_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='textexplanation',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textexplanation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='textexplanation',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(set_existing_records_to_completed, reverse_code=migrations.RunPython.noop),
    ]
