# Generated by Django 5.0.10 on 2025-02-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0017_textexplanation_error_textexplanation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamestory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textexplanation',
            name='user',
        ),
        migrations.AddField(
            model_name='gamestory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textexplanation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textexplanation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
