# Generated by Django 5.0.10 on 2025-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_caller', '0018_remove_apirequest_user_remove_gamestory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinteraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
