volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  production_django_static: {}
  production_redis_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ai_text_game_production_django
    restart: unless-stopped
    volumes:
      - production_django_media:/app/ai_text_game/media
      - production_django_static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.secrets
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ai_text_game_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.secrets

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: ai_text_game_production_traefik
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6
    restart: unless-stopped
    volumes:
      - production_redis_data:/data


  celeryworker:
    <<: *django
    image: ai_text_game_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ai_text_game_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: ai_text_game_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: ai_text_game_production_nginx
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
      - production_django_static:/usr/share/nginx/static:ro
