services:
  docs:
    image: ai_text_game_local_docs
    container_name: ai_text_game_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ai_text_game:/app/ai_text_game:z
    ports:
      - '9000:9000'
    command: /start-docs
